In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
df = pd.read_csv("canada_per_capita_income.csv")
df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [3]:
x=df['year']
y=df['per capita income (US$)']
x=x.values.reshape(-1,1)
y=y.values.reshape(-1,1)
print(x.shape)

(47, 1)


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(42, 1)
(5, 1)
(42, 1)
(5, 1)


In [28]:
model = LinearRegression()
model.fit(x_train, y_train)
predicted = model.predict(x_test)
score= model.score(x_test,y_test)
print(score)

0.9774025563842987


In [29]:
model.coef_

array([[834.97679908]])

In [30]:
model.intercept_

array([-1645139.28984179])

In [32]:
model.predict([[2020]])

array([[41513.84429722]])