In [2]:
def indore():
    '''this is a function'''
    print("hello world")
    print("ok")
indore()
help(indore)

hello world
ok
Help on function indore in module __main__:

indore()
    this is a function



In [4]:
d= {"A":"Indore", 5:65, "goa":45}   #any maths operation is performed on the keys defaultly
print(d["A"])
print(type(d))

Indore
<class 'dict'>


In [5]:
import numpy as np

x = np.arange(50)
print("Array from 0 to 50:")
print(x)

x = np.arange(10, 50)
print("Array from 10 to 50:")
print(x)



Array from 0 to 50:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
t=(4,3,2,1)   #cant add or change any value in the tuple
print(t)      #can take different data types
print(t[0])

(4, 3, 2, 1)
4


In [8]:
s={1,2,3,4,5,6,7,8,2,2,2,2,2}  #doesnt repeat elements     union |   difference -      intersection &    symmetric  ^
print(s)                       # only one data type

{1, 2, 3, 4, 5, 6, 7, 8}


In [14]:
import numpy as np

x = np.ones((4,4))
print(x)

x[1:3,1:3] = 0
print(x)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [16]:
import re
pattern = re.compile(r"abc")
pattern = pattern.finditer(text_to_search)
for match in matches:
    print(match)

NameError: name 'text_to_search' is not defined